# This is a basic workflow to help you get started with Actions

name: Publish to Factorio mod portal

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - "main"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@main

      # Validation
      - name: Validate mod
        uses: TheBrutalX/factorio-mod-uploader-action@v1
        with:
          action: validate

      # Packing mod
      - name: Create zip
        uses: TheBrutalX/factorio-mod-uploader-action@v1
        with:
          action: compress

      # Upload mod
      - name: Upload Mod
        uses: TheBrutalX/factorio-mod-uploader-action@v1
        with:
          action: upload
          factorio-api-key: ${{ secrets.FACTORIO_API_KEY }}
